### ISSUE TITLE
`bufWritePre ` * error 

### ISSUE THREAD

**Issue by OmiChrome** [aaron-p1/virt-notes.nvim#1]
![image](https://github.com/aaron-p1/virt-notes.nvim/assets/108952834/c3dc2779-3b7f-429d-9970-eae965b94f0b)

info : 
OS : window 11 | no wsl
nvim :  0.9.0

**Comment by aaron-p1** [comment]
It should be fixed now, but please let me know if it is still broken because I did not test this in Windows

**Comment by OmiChrome** [comment]
working FINE Thx

but one ISSUE, 
how to LAZYLOAD? lazyloading remove notes

**Comment by aaron-p1** [comment]
Should be working now since 486cd72dff5bc4244934ced7c3a94a849f7bcc5e
