### ISSUE TITLE
Error when restoring session

### ISSUE THREAD

**Issue by haraldan** [aaron-p1/virt-notes.nvim#4]
Using this plugin, restoring a Neovim session produces the following error, unless the current buffer has virtual notes:

Error: E484: Can't open file /home/ds/.local/share/nvim/virt_notes/_home_ds_.dotfiles_.config_nvim_lua_options.lua.txt

**Comment by aaron-p1** [comment]
Sorry, I cannot reproduce this. This error should be thrown in this line that gets executed when loading buffers https://github.com/aaron-p1/virt-notes.nvim/blob/1c43e82cc996e3df570b9d08a305bc7e5135ab0e/lua/virt-notes/notes.lua#L67 but I use a `pcall` to not let it throw errors.

I also tested creating a session with  `:mksession` and restoring it with `nvim -S session`, but that works for me.

Please provide me a way to reproduce this.

**Comment by haraldan** [comment]
You are right, I think this is an issue of the auto-session plugin, not this one. I also cannot reproduce this when restoring a session manually.

**Comment by haraldan** [comment]
Also, thank you for the fantastic plugin! I've been looking for exactly this functionality and wasn't able to find it anywhere else.
